defaults: 
  bc_pattern: CCCCCCCCCCCCCCCCNNNNNNNNNN
  cell_number: 1000

output_dir: "results"

file_layout: "config/file_layout.yaml"
samples: "config/samples.csv"

kraken:
  threads: 8
  db_paths:
    virus: /data/repository/kraken2_contaminome/virus_db