umi_tools_whitelist:
  whitelist: {sample}_whitelist.txt

umi_tools_extract:
  read_one: {sample}_extracted_R1.fastq.gz
  read_two: {sample}_extracted_R2.fastq.gz

kraken:
  report: {sample}_mapped_to_{db}.k2report
  output: {sample}_mapped_to_{db}.kraken2